### ISSUE TITLE
GCE support

### ISSUE THREAD

**Issue by ant31** [kubespray/k8s-integration-tests#3]
Having a lot of issue with EC2 we will run test un GCE, it's faster to boot and easier to manage.
We probably leave one build on aws to test it

**Comment by ant31** [comment]
@jcsirot have you force push the branch gce ?

the builds were working already:
https://travis-ci.org/ansibl8s/k8s-integration-tests/builds/105920444

**Comment by jcsirot** [comment]
I made a mistake when pushing my "gce" branch. I reverted my commits and it should be fixed now.

**Comment by ant31** [comment]
I should have create a ticket before.
